name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement", "triage"]
projects: ["octo-org/1"]
assignees:
  - octocat
body:
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: What is your name?
      placeholder: ex. Sertha Taweewattana
    validations:
      required: true
  - type: dropdown
    id: request-type
    attributes:
      label: Type of request?
      description: Select the type of your request
      options:
        - New Feature
        - Improvement
      default: 0
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: What is the OS which you want to suggest?
      multiple: false
      options:
        - Windows
        - macOS
        - Linux
        - All Platforms
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: What are the details of your suggestion?
      description: Explain what do you want
      placeholder: Feature details!
    validations:
      required: true